# Generated by Django 3.2.9 on 2021-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211117_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profiles/user-default.png', upload_to='profiles/'),
        ),
    ]
